### ISSUE TITLE
How do I generate an anonymousId using php?

### ISSUE THREAD

**Issue by ivan006** [rudderlabs/rudder-php-sdk#1]
I see the JS sdk has functionality to allow you to generate one. As said in this statement 
```
NOTE: The anonymousId is a UUID (Universally Unique Identifier) generated to uniquely identify the user. Also, if it is provided by the user using the setAnonymousId method, the user-specified anonymousId overrides the SDK-generated one.
```
Is there a way to do it without JS or?

**Comment by arnab-p** [comment]
@ivan006 The client SDKs like Javascript are intended to track one user at a time, and that's why we generate `anonymousId` for every user in the SDK and pass it along with every event. But, server-side SDKs are intended to track multiple users at a time. So, you can think of it as a bulk upload from your servers. Thus, we don't generate `anoymousId` at the server-side SDK. If your use case needs an `anonymousId` in the event, you can pass it with the call by yourself by passing a UUID.
